version: "3.8"

networks:
  app:
    driver: bridge

services:
  postgres:
    image: postgres:14.6
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: bash -c "foreman start"
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: production
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
      - ./log:/app/log
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - app

volumes:
  redis_data:
  gem_cache:
